//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> CategoryProductID { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        [DisplayName("Tên sản phẩm")]
        public string Name { get; set; }
       
        public string Desciption { get; set; }
        [Required(ErrorMessage = "Giá sản phẩm không được để trống")]
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        //[Required(ErrorMessage = "Hình ảnh sản phẩm không được để trống")]
        public HttpPostedFileBase ImageFile { get; set; }
        public string Image { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        [Required(ErrorMessage = "Số lượng sản phẩm không được để trống")]
        public Nullable<int> Count { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Shop Shop { get; set; }

    }
}
