//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid ShopID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        [Required(ErrorMessage = "Tên shop không được để trống")]
        [Remote("IsExist", "Shops", AdditionalFields = "Id",
                ErrorMessage = "Tên cửa hàng đã tồn tại")]
        public string NameShop { get; set; }
        [Required(ErrorMessage = "Địa chỉ shop không được để trống")]
        public string Address { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual User User { get; set; }
        public virtual City City { get; set; }
    }
}
