//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Shops = new HashSet<Shop>();
        }
        
        public System.Guid UserID { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Họ không được để trống")]
        public string FirstName { get; set; }
        [DisplayName("Họ và tên")]
        public string FullName { get { return string.Format("{0} {1}", FirstName, LastName); } }
        [Required(ErrorMessage = "Ngày sinh không được để trống")]      
        [Column("DOB", TypeName = "DateTime")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> BirthDay { get; set; }
        [Required(ErrorMessage = "Điện thoại không được để trống")]
        [RegularExpression(@"^(0)(\d{9})$", ErrorMessage = "Số điện thoại không hơp lệ")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }
        [Required(ErrorMessage = "CMND không được để trống")]
        [DisplayName("CMND")]
        [RegularExpression(@"(\d{9})$", ErrorMessage = "CMND không hợp lệ")]
        public string CMNN { get; set; }
        //[Required(ErrorMessage = "Tỉnh thành không được để trống")]
        public Nullable<System.Guid> CityID { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập là bắt buộc")]
     
        [Remote("IsExist", "Users", AdditionalFields = "Id",
                ErrorMessage = "Tên Đăng nhập đã tồn tại")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Mật khẩu đăng nhập là bắt buộc")]
        [StringLength(100, ErrorMessage = "Mật khẩu phải dài hơn 8 kí tự", MinimumLength = 8)]
       [DataType(DataType.Password)]
        public string PassWord { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
      
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
